<a href="https://colab.research.google.com/github/Endalebob/ml-track/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [32]:
import itertools

my_list = ['A', 'B', 'C']
combinations = itertools.combinations(my_list, 2)

for _ in combinations:
  print(_)

('A', 'B')
('A', 'C')
('B', 'C')


**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [33]:
import itertools

sequence = itertools.cycle(['Python', 'is', 'fun'])

for _ in range(10):
    print(next(sequence))


Python
is
fun
Python
is
fun
Python
is
fun
Python


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [34]:
import glob

python_files = glob.glob('*.py')

for file in python_files:
    print(file)

backtrack.py
dynamic_range_sum.py


**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [20]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [35]:
from bs4 import BeautifulSoup

def content_extractor(content):
  soup = BeautifulSoup(content,"html.parser")
  paragraph = soup.find('p')
  if paragraph:
    return paragraph.get_text()
  return None

content = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"

content_extractor(content)

'AI is transforming the world'

**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [36]:
import re

def word_replace(pattern,replace,string):
  return re.sub(pattern,replace,string)

string = "Welcome to AI. AI is transforming the world"
pattern = r'AI'
replace = 'Artificial Intelligence'
replaced_string = word_replace(pattern,replace,string)

replaced_string

'Welcome to Artificial Intelligence. Artificial Intelligence is transforming the world'

**CP6**: Create a numpy array of 10 zeros.

In [37]:
import numpy as np

ten_zeros = np.zeros(10)
ten_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**CP7** Create a numpy array of the integers from 10 to 49.

In [38]:
ten_to_49 = np.arange(10,50)
ten_to_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [39]:
oneD = np.arange(9)
threeD = oneD.reshape(3,3)
threeD

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?




<h2>Machine learning models require large amounts of data for several reasons:</h2>

<h3 style="color: blue;">Generalization:</h3>
<p>Machine learning models aim to learn patterns and make predictions based on the data they are trained on. With more data, models can generalize better, meaning they can learn more representative and accurate patterns that are applicable to unseen data.</p>

<h3 style="color: blue;">Reducing Bias and Variance:</h3>
<p>Large datasets can help mitigate both bias and variance in machine learning models. Bias refers to the model's tendency to consistently underfit or oversimplify the data, while variance refers to the model's sensitivity to the training data, resulting in overfitting. With more data, models have a better chance of capturing the true underlying patterns without being overly influenced by noise or outliers.</p>

<h3 style="color: blue;">Feature Representation:</h3>
<p>Machine learning models often require a sufficient amount of data to adequately represent the complexity and diversity of features present in the real-world problem. If the dataset is too small, it may not cover the full range of variations in the features, leading to poor model performance and limited applicability.</p>


**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

<h2>AI can be used in adversarial ways, it can be exploited or manipulated for harmful purposes.</h2>
<p>Here are two ways AI can be misused and some potential preventive measures:</p>

<h3 style="color: red;">Adversarial Attacks on AI Models:</h3>
<p>AI models can be susceptible to adversarial attacks, where malicious actors intentionally manipulate or perturb input data to deceive or mislead the model's predictions. These attacks can lead to incorrect decisions, such as misclassifying objects in image recognition or manipulating natural language processing models.</p>
<p>To prevent adversarial attacks, techniques like adversarial training, input sanitization, and robust model architectures can be employed to enhance the model's resilience against adversarial manipulations.</p>

<h3 style="color: red;">AI-driven Disinformation and Manipulation:</h3>
<p>AI can be employed to create and spread disinformation, propaganda, and fake media content, leading to social and political unrest. AI-powered text generation and deepfake technologies can be misused to create convincing fake news, misinformation, or impersonate individuals.</p>
<p>Countermeasures to combat AI-driven disinformation include fact-checking initiatives, media literacy programs, and the development of AI algorithms to detect and filter out fake content.</p>

<p>Preventive measures to address adversarial uses of AI include:</p>

<ul>
  <li><span style="color: blue;">Robust and Secure Model Design:</span> Developing AI models with built-in security measures, such as secure architectures, encryption, and anomaly detection, to prevent unauthorized access and tampering.</li>
  <li><span style="color: blue;">Ethical Frameworks and Regulations:</span> Establishing clear ethical guidelines, legal frameworks, and regulations to ensure responsible AI development and deployment, including the identification and mitigation of potential adversarial risks.</li>
  <li><span style="color: blue;">Adversarial Testing and Evaluation:</span> Conducting rigorous testing and evaluation of AI models to identify vulnerabilities and weaknesses, including adversarial testing to assess the model's resilience against attacks.</li>
  <li><span style="color: blue;">Ongoing Research and Collaboration:</span> Encouraging continuous research and collaboration among AI practitioners, researchers, policymakers, and other stakeholders to address emerging adversarial challenges and develop effective countermeasures.</li>
  <li><span style="color: blue;">Transparency and Accountability:</span> Promoting transparency in AI systems by providing explanations of model decisions and maintaining accountability for the use of AI technology, particularly in critical domains such as healthcare, finance, and security.</li>
</ul>
